
version: '3.8'
services:
  activemq:
    image: apache/activemq-classic:5.18.3
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: fleetpulse-app
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fleetdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - activemq
      - db
